package com.alexandria.app.ui.components

data class NamedEmoji(val name: String, val emoji: String)

data class EmojiCategory(val key: String, val label: String, val items: List<NamedEmoji>)

object CharacterEmojis {

    val categories: List<EmojiCategory> = listOf(
        EmojiCategory(
            "personas", "Personas",
            listOf(
                NamedEmoji("Persona", "🧑"),
                NamedEmoji("Hombre", "👨"),
                NamedEmoji("Mujer", "👩"),
                NamedEmoji("Niño", "👦"),
                NamedEmoji("Niña", "👧"),
                NamedEmoji("Bebé", "👶"),
                NamedEmoji("Anciano", "👴"),
                NamedEmoji("Anciana", "👵"),
                NamedEmoji("Princesa", "👸"),
                NamedEmoji("Príncipe", "🤴"),
                NamedEmoji("Policía", "👮"),
                NamedEmoji("Detective", "🕵️"),
                NamedEmoji("Astronauta", "👨‍🚀"),
                NamedEmoji("Médico", "👨‍⚕️"),
                NamedEmoji("Médica", "👩‍⚕️"),
                NamedEmoji("Cocinero", "👨‍🍳"),
                NamedEmoji("Cocinera", "👩‍🍳"),
                NamedEmoji("Estudiante", "👨‍🎓"),
                NamedEmoji("Profesor", "👨‍🏫"),
                NamedEmoji("Profesora", "👩‍🏫"),
                NamedEmoji("Granjero", "👨‍🌾"),
                NamedEmoji("Mecánico", "👨‍🔧"),
                NamedEmoji("Ejecutivo", "👨‍💼"),
                NamedEmoji("Programador", "👨‍💻"),
                NamedEmoji("Artista", "👨‍🎨"),
                NamedEmoji("Artista (mujer)", "👩‍🎨"),
                NamedEmoji("Cantante", "👨‍🎤"),
                NamedEmoji("Papá Noel", "🧑‍🎄"),
                NamedEmoji("Piloto", "🧑‍✈️"),
                NamedEmoji("Científico", "👨‍🔬"),
                NamedEmoji("Científica", "👩‍🔬")
            )
        ),
        EmojiCategory(
            "animales", "Animales",
            listOf(
                NamedEmoji("Perro", "🐶"),
                NamedEmoji("Gato", "🐱"),
                NamedEmoji("Ratón", "🐭"),
                NamedEmoji("Hámster", "🐹"),
                NamedEmoji("Conejo", "🐰"),
                NamedEmoji("Zorro", "🦊"),
                NamedEmoji("Oso", "🐻"),
                NamedEmoji("Panda", "🐼"),
                NamedEmoji("Koala", "🐨"),
                NamedEmoji("Tigre", "🐯"),
                NamedEmoji("León", "🦁"),
                NamedEmoji("Vaca", "🐮"),
                NamedEmoji("Cerdo", "🐷"),
                NamedEmoji("Rana", "🐸"),
                NamedEmoji("Mono", "🐵"),
                NamedEmoji("Gallina", "🐔"),
                NamedEmoji("Pingüino", "🐧"),
                NamedEmoji("Pájaro", "🐦"),
                NamedEmoji("Búho", "🦉"),
                NamedEmoji("Águila", "🦅"),
                NamedEmoji("Murciélago", "🦇"),
                NamedEmoji("Lobo", "🐺"),
                NamedEmoji("Caballo", "🐴"),
                NamedEmoji("Unicornio", "🦄"),
                NamedEmoji("Abeja", "🐝"),
                NamedEmoji("Mariposa", "🦋"),
                NamedEmoji("Tortuga", "🐢"),
                NamedEmoji("Serpiente", "🐍"),
                NamedEmoji("Tiburón", "🦈"),
                NamedEmoji("Delfín", "🐬"),
                NamedEmoji("Ballena", "🐋"),
                NamedEmoji("Cocodrilo", "🐊"),
                NamedEmoji("Elefante", "🐘"),
                NamedEmoji("Camello", "🐫"),
                NamedEmoji("Loro", "🦜"),
                NamedEmoji("Flamenco", "🦩"),
                NamedEmoji("Pulpo", "🐙"),
                NamedEmoji("Calamar", "🦑"),
                NamedEmoji("Cangrejo", "🦀"),
                NamedEmoji("Pez", "🐠"),
                NamedEmoji("Dragón", "🐉"),
                NamedEmoji("Dinosaurio", "🦖")
            )
        ),
        EmojiCategory(
            "naturaleza", "Naturaleza",
            listOf(
                NamedEmoji("Rosa", "🌹"),
                NamedEmoji("Flor", "🌸"),
                NamedEmoji("Margarita", "🌼"),
                NamedEmoji("Girasol", "🌻"),
                NamedEmoji("Tulipán", "🌷"),
                NamedEmoji("Árbol", "🌳"),
                NamedEmoji("Pino", "🌲"),
                NamedEmoji("Palmera", "🌴"),
                NamedEmoji("Cactus", "🌵"),
                NamedEmoji("Trébol", "🍀"),
                NamedEmoji("Planta", "🌿"),
                NamedEmoji("Seta", "🍄"),
                NamedEmoji("Ramo de flores", "💐"),
                NamedEmoji("Ola", "🌊"),
                NamedEmoji("Volcán", "🌋"),
                NamedEmoji("Montaña", "⛰️"),
                NamedEmoji("Amanecer", "🌄"),
                NamedEmoji("Atardecer", "🌅"),
                NamedEmoji("Arcoíris", "🌈"),
                NamedEmoji("Estrella", "⭐"),
                NamedEmoji("Estrella brillante", "🌟"),
                NamedEmoji("Destellos", "✨"),
                NamedEmoji("Rayo", "⚡"),
                NamedEmoji("Fuego", "🔥"),
                NamedEmoji("Gota de agua", "💧"),
                NamedEmoji("Nieve", "❄️"),
                NamedEmoji("Sol", "☀️"),
                NamedEmoji("Luna", "🌙"),
                NamedEmoji("Nube", "☁️"),
                NamedEmoji("Tierra", "🌍"),
                NamedEmoji("Tornado", "🌀")
            )
        ),
        EmojiCategory(
            "comida", "Comida",
            listOf(
                NamedEmoji("Manzana", "🍎"),
                NamedEmoji("Naranja", "🍊"),
                NamedEmoji("Limón", "🍋"),
                NamedEmoji("Plátano", "🍌"),
                NamedEmoji("Sandía", "🍉"),
                NamedEmoji("Uvas", "🍇"),
                NamedEmoji("Fresa", "🍓"),
                NamedEmoji("Cerezas", "🍒"),
                NamedEmoji("Melocotón", "🍑"),
                NamedEmoji("Mango", "🥭"),
                NamedEmoji("Piña", "🍍"),
                NamedEmoji("Coco", "🥥"),
                NamedEmoji("Kiwi", "🥝"),
                NamedEmoji("Tomate", "🍅"),
                NamedEmoji("Berenjena", "🍆"),
                NamedEmoji("Aguacate", "🥑"),
                NamedEmoji("Brócoli", "🥦"),
                NamedEmoji("Maíz", "🌽"),
                NamedEmoji("Zanahoria", "🥕"),
                NamedEmoji("Queso", "🧀"),
                NamedEmoji("Huevo", "🥚"),
                NamedEmoji("Pan", "🍞"),
                NamedEmoji("Hamburguesa", "🍔"),
                NamedEmoji("Pizza", "🍕"),
                NamedEmoji("Taco", "🌮"),
                NamedEmoji("Sushi", "🍣"),
                NamedEmoji("Helado", "🍦"),
                NamedEmoji("Tarta", "🍰"),
                NamedEmoji("Chocolate", "🍫"),
                NamedEmoji("Caramelo", "🍬"),
                NamedEmoji("Palomitas", "🍿"),
                NamedEmoji("Café", "☕"),
                NamedEmoji("Té", "🍵"),
                NamedEmoji("Cerveza", "🍺"),
                NamedEmoji("Vino", "🍷")
            )
        ),
        EmojiCategory(
            "actividades", "Actividades",
            listOf(
                NamedEmoji("Fútbol", "⚽"),
                NamedEmoji("Baloncesto", "🏀"),
                NamedEmoji("Tenis", "🎾"),
                NamedEmoji("Béisbol", "⚾"),
                NamedEmoji("Fútbol americano", "🏈"),
                NamedEmoji("Voleibol", "🏐"),
                NamedEmoji("Billar", "🎱"),
                NamedEmoji("Ping pong", "🏓"),
                NamedEmoji("Bádminton", "🏸"),
                NamedEmoji("Golf", "⛳"),
                NamedEmoji("Pesca", "🎣"),
                NamedEmoji("Natación", "🏊"),
                NamedEmoji("Ciclismo", "🚴"),
                NamedEmoji("Hípica", "🏇"),
                NamedEmoji("Escalada", "🧗"),
                NamedEmoji("Snowboard", "🏂"),
                NamedEmoji("Skate", "🛹"),
                NamedEmoji("Boxeo", "🥊"),
                NamedEmoji("Judo", "🥋"),
                NamedEmoji("Atletismo", "🎽"),
                NamedEmoji("Trofeo", "🏆"),
                NamedEmoji("Medalla de oro", "🥇"),
                NamedEmoji("Dardos", "🎯"),
                NamedEmoji("Dados", "🎲"),
                NamedEmoji("Rompecabezas", "🧩"),
                NamedEmoji("Ajedrez", "♟️"),
                NamedEmoji("Videojuegos", "🎮"),
                NamedEmoji("Arte", "🎨"),
                NamedEmoji("Micrófono", "🎤"),
                NamedEmoji("Guitarra", "🎸"),
                NamedEmoji("Violín", "🎻"),
                NamedEmoji("Tambor", "🥁"),
                NamedEmoji("Piano", "🎹"),
                NamedEmoji("Música", "🎼"),
                NamedEmoji("Circo", "🎪")
            )
        ),
        EmojiCategory(
            "objetos", "Objetos",
            listOf(
                NamedEmoji("Corona", "👑"),
                NamedEmoji("Diamante", "💎"),
                NamedEmoji("Daga", "🗡️"),
                NamedEmoji("Espadas", "⚔️"),
                NamedEmoji("Escudo", "🛡️"),
                NamedEmoji("Arco", "🏹"),
                NamedEmoji("Bola de cristal", "🔮"),
                NamedEmoji("Rosario", "📿"),
                NamedEmoji("Llave", "🔑"),
                NamedEmoji("Llave antigua", "🗝️"),
                NamedEmoji("Libro abierto", "📖"),
                NamedEmoji("Libros", "📚"),
                NamedEmoji("Pergamino", "📜"),
                NamedEmoji("Pluma", "✒️"),
                NamedEmoji("Lápiz", "✏️"),
                NamedEmoji("Chincheta", "📌"),
                NamedEmoji("Mapa", "🗺️"),
                NamedEmoji("Brújula", "🧭"),
                NamedEmoji("Reloj de arena", "⏳"),
                NamedEmoji("Despertador", "⏰"),
                NamedEmoji("Imán", "🧲"),
                NamedEmoji("Bombilla", "💡"),
                NamedEmoji("Linterna", "🔦"),
                NamedEmoji("Vela", "🕯️"),
                NamedEmoji("Regalo", "🎁"),
                NamedEmoji("Varita mágica", "🪄"),
                NamedEmoji("Escoba", "🧹"),
                NamedEmoji("Engranaje", "⚙️"),
                NamedEmoji("Martillo", "🔨"),
                NamedEmoji("Caja", "📦"),
                NamedEmoji("Carta", "✉️"),
                NamedEmoji("Dinero", "💰"),
                NamedEmoji("Gafas", "👓"),
                NamedEmoji("Sombrero", "🎩"),
                NamedEmoji("Gorra", "🧢"),
                NamedEmoji("Maletín", "💼")
            )
        ),
        EmojiCategory(
            "fantasia", "Fantasía",
            listOf(
                NamedEmoji("Mago", "🧙"),
                NamedEmoji("Maga", "🧙‍♀️"),
                NamedEmoji("Elfo", "🧝"),
                NamedEmoji("Vampiro", "🧛"),
                NamedEmoji("Zombi", "🧟"),
                NamedEmoji("Hada", "🧚"),
                NamedEmoji("Sirena", "🧜"),
                NamedEmoji("Genio", "🧞"),
                NamedEmoji("Superhéroe", "🦸"),
                NamedEmoji("Supervillano", "🦹"),
                NamedEmoji("Dragón", "🐉"),
                NamedEmoji("Demonio", "👹"),
                NamedEmoji("Ogro", "👺"),
                NamedEmoji("Fantasma", "👻"),
                NamedEmoji("Calavera", "💀"),
                NamedEmoji("Robot", "🤖"),
                NamedEmoji("Alienígena", "👽"),
                NamedEmoji("Monstruo", "👾"),
                NamedEmoji("Troll", "🧌"),
                NamedEmoji("Unicornio", "🦄"),
                NamedEmoji("Araña", "🕷️"),
                NamedEmoji("Telaraña", "🕸️"),
                NamedEmoji("Tridente", "🔱"),
                NamedEmoji("Explosión", "💥"),
                NamedEmoji("Cometa", "☄️")
            )
        ),
        EmojiCategory(
            "detectives", "Detectives",
            listOf(
                NamedEmoji("Detective", "🕵️"),
                NamedEmoji("Detective (mujer)", "🕵️‍♀️"),
                NamedEmoji("Lupa", "🔍"),
                NamedEmoji("Lupa inclinada", "🔎"),
                NamedEmoji("Llave antigua", "🗝️"),
                NamedEmoji("Llave", "🔑"),
                NamedEmoji("Linterna", "🔦"),
                NamedEmoji("Portapapeles", "📋"),
                NamedEmoji("Notas", "📝"),
                NamedEmoji("Carpeta", "📂"),
                NamedEmoji("Computadora", "🖥️"),
                NamedEmoji("Computadora portátil", "💻"),
                NamedEmoji("Teléfono", "📞"),
                NamedEmoji("Cámara", "📷"),
                NamedEmoji("Coche patrulla", "🚔"),
                NamedEmoji("Sirena", "🚨"),
                NamedEmoji("Balanza de justicia", "⚖️"),
                NamedEmoji("Huellas", "👣"),
                NamedEmoji("Maletín", "💼"),
                NamedEmoji("Sombrero", "🎩"),
                NamedEmoji("Ciudad de noche", "🌃"),
                NamedEmoji("Interrogante", "❓")
            )
        ),
        EmojiCategory(
            "misterio", "Misterio",
            listOf(
                NamedEmoji("Bola de cristal", "🔮"),
                NamedEmoji("Luna", "🌙"),
                NamedEmoji("Luna nueva", "🌑"),
                NamedEmoji("Vela", "🕯️"),
                NamedEmoji("Búho", "🦉"),
                NamedEmoji("Murciélago", "🦇"),
                NamedEmoji("Araña", "🕷️"),
                NamedEmoji("Telaraña", "🕸️"),
                NamedEmoji("Fantasma", "👻"),
                NamedEmoji("Calavera", "💀"),
                NamedEmoji("Vampiro", "🧛"),
                NamedEmoji("Zombi", "🧟"),
                NamedEmoji("Sombrero", "🎩"),
                NamedEmoji("Llave antigua", "🗝️"),
                NamedEmoji("Reloj antiguo", "🕰️"),
                NamedEmoji("Casa abandonada", "🏚️"),
                NamedEmoji("Castillo", "🏰"),
                NamedEmoji("Ataúd", "⚰️"),
                NamedEmoji("Lápida", "🪦"),
                NamedEmoji("Amuleto", "🧿"),
                NamedEmoji("Niebla", "🌫️"),
                NamedEmoji("Tormenta", "⛈️"),
                NamedEmoji("Lluvia", "🌧️"),
                NamedEmoji("Interrogante", "❓"),
                NamedEmoji("Ojo", "👁️"),
                NamedEmoji("Candado cerrado", "🔐"),
                NamedEmoji("Candado abierto", "🔓")
            )
        ),
        EmojiCategory(
            "historia", "Historia",
            listOf(
                NamedEmoji("Templo griego", "🏛️"),
                NamedEmoji("Castillo", "🏰"),
                NamedEmoji("Castillo japonés", "🏯"),
                NamedEmoji("Estatua moai", "🗿"),
                NamedEmoji("Torii", "⛩️"),
                NamedEmoji("Mezquita", "🕌"),
                NamedEmoji("Iglesia", "⛪"),
                NamedEmoji("Sinagoga", "🕍"),
                NamedEmoji("Templo hindú", "🛕"),
                NamedEmoji("Ánfora", "🏺"),
                NamedEmoji("Daga", "🗡️"),
                NamedEmoji("Espadas", "⚔️"),
                NamedEmoji("Escudo", "🛡️"),
                NamedEmoji("Arco", "🏹"),
                NamedEmoji("Corona", "👑"),
                NamedEmoji("Pergamino", "📜"),
                NamedEmoji("Reloj de arena", "⏳"),
                NamedEmoji("Reloj antiguo", "🕰️"),
                NamedEmoji("Ancla", "⚓"),
                NamedEmoji("Bandera pirata", "🏴‍☠️"),
                NamedEmoji("Brújula", "🧭"),
                NamedEmoji("Globo terráqueo", "🌍"),
                NamedEmoji("Trofeo", "🏆"),
                NamedEmoji("Medalla", "🎖️"),
                NamedEmoji("Trompeta", "🎺")
            )
        ),
        EmojiCategory(
            "drama", "Drama",
            listOf(
                NamedEmoji("Máscaras de teatro", "🎭"),
                NamedEmoji("Claqueta", "🎬"),
                NamedEmoji("Cámara de cine", "🎥"),
                NamedEmoji("Película", "🎞️"),
                NamedEmoji("Proyector", "📽️"),
                NamedEmoji("Entradas", "🎟️"),
                NamedEmoji("Boleto", "🎫"),
                NamedEmoji("Circo", "🎪"),
                NamedEmoji("Micrófono", "🎤"),
                NamedEmoji("Bailarina", "💃"),
                NamedEmoji("Bailarín", "🕺"),
                NamedEmoji("Zapatillas de ballet", "🩰"),
                NamedEmoji("Piano", "🎹"),
                NamedEmoji("Violín", "🎻"),
                NamedEmoji("Trompeta", "🎺"),
                NamedEmoji("Saxofón", "🎷"),
                NamedEmoji("Guitarra", "🎸"),
                NamedEmoji("Partitura", "🎼"),
                NamedEmoji("Nota musical", "🎵"),
                NamedEmoji("Premio", "🏆"),
                NamedEmoji("Medalla", "🥇"),
                NamedEmoji("Estrella", "🌟"),
                NamedEmoji("Corazón roto", "💔"),
                NamedEmoji("Miedo", "😱"),
                NamedEmoji("Terror", "😨"),
                NamedEmoji("Payaso", "🤡")
            )
        ),
        EmojiCategory(
            "simbolos", "Símbolos",
            listOf(
                NamedEmoji("Corazón rojo", "❤️"),
                NamedEmoji("Corazón amarillo", "💛"),
                NamedEmoji("Corazón verde", "💚"),
                NamedEmoji("Corazón azul", "💙"),
                NamedEmoji("Corazón morado", "💜"),
                NamedEmoji("Corazón negro", "🖤"),
                NamedEmoji("Corazón roto", "💔"),
                NamedEmoji("Corazones", "💕"),
                NamedEmoji("Corazón brillante", "💖"),
                NamedEmoji("Estrella", "⭐"),
                NamedEmoji("Destellos", "✨"),
                NamedEmoji("Cometa", "💫"),
                NamedEmoji("Rayo", "⚡"),
                NamedEmoji("Fuego", "🔥"),
                NamedEmoji("Sol", "☀️"),
                NamedEmoji("Luna", "🌙"),
                NamedEmoji("Arcoíris", "🌈"),
                NamedEmoji("Reciclaje", "♻️"),
                NamedEmoji("Aprobado", "✅"),
                NamedEmoji("Equis", "❌"),
                NamedEmoji("Advertencia", "⚠️"),
                NamedEmoji("Cien", "💯"),
                NamedEmoji("Prohibido", "🚫"),
                NamedEmoji("Interrogante", "❓"),
                NamedEmoji("Exclamación", "❗"),
                NamedEmoji("Pica", "♠️"),
                NamedEmoji("Corazón de cartas", "♥️"),
                NamedEmoji("Diamante de cartas", "♦️"),
                NamedEmoji("Trébol de cartas", "♣️")
            )
        )
    )

    val allItems: List<NamedEmoji> = categories.flatMap { it.items }

    fun search(query: String): List<NamedEmoji> {
        val q = normalize(query)
        if (q.isEmpty()) return allItems
        return allItems.filter { normalize(it.name).contains(q) || normalize(it.emoji).contains(query.trim()) }
    }

    fun defaultForName(name: String): String {
        val n = normalize(name)
        val rules = listOf(
            "maga" to "🧙‍♀️", "hechicera" to "🧙‍♀️", "bruja" to "🧙‍♀️",
            "mago" to "🧙", "hechicero" to "🧙", "brujo" to "🧙", "encantador" to "🧙",
            "reina" to "👸",
            "rey" to "🤴", "emperador" to "🤴", "principe" to "🤴",
            "princesa" to "👸",
            "dragon" to "🐉", "caballero" to "🛡️", "heroe" to "🦸", "heroina" to "🦸‍♀️",
            "villano" to "🦹", "villana" to "🦹‍♀️",
            "lobo" to "🐺", "loba" to "🐺", "zorro" to "🦊", "zorra" to "🦊",
            "gato" to "🐱", "gata" to "🐱", "perro" to "🐶", "perra" to "🐶",
            "cuervo" to "🦅", "cuerv" to "🦅",
            "hada" to "🧚", "elfo" to "🧝", "elfa" to "🧝",
            "vampiro" to "🧛", "vampira" to "🧛", "zombi" to "🧟", "zombie" to "🧟",
            "fantasma" to "👻", "esqueleto" to "💀", "calavera" to "💀",
            "robot" to "🤖", "alien" to "👽", "extraterrestre" to "👽",
            "detective" to "🕵️", "investigador" to "🕵️", "inspector" to "🕵️",
            "policia" to "👮", "soldado" to "🪖", "guerrero" to "⚔️", "guerrera" to "⚔️",
            "pirata" to "🦜", "astronauta" to "🚀", "cientifico" to "🔬",
            "profesor" to "🧑‍🏫", "profesora" to "🧑‍🏫", "maestro" to "🧑‍🏫",
            "medico" to "🧑‍⚕️", "doctor" to "🧑‍⚕️", "doctora" to "🧑‍⚕️",
            "enfermero" to "🧑‍⚕️", "enfermera" to "🧑‍⚕️",
            "chef" to "👨‍🍳", "cocinero" to "👨‍🍳", "cocinera" to "👩‍🍳",
            "nino" to "👦", "nina" to "👧", "bebe" to "👶",
            "hombre" to "👨", "varon" to "👨", "chico" to "👦",
            "mujer" to "👩", "chica" to "👧", "dama" to "👩",
            "leon" to "🦁", "tigre" to "🐯", "tigresa" to "🐯",
            "oso" to "🐻", "osa" to "🐻", "elefante" to "🐘", "mono" to "🐵",
            "serpiente" to "🐍", "caballo" to "🐴", "yegua" to "🐴", "unicornio" to "🦄",
            "raton" to "🐭", "conejo" to "🐰", "rana" to "🐸", "sapo" to "🐸",
            "abeja" to "🐝", "mariposa" to "🦋", "pajaro" to "🐦", "ave" to "🐦",
            "aguila" to "🦅", "buho" to "🦉", "lechuza" to "🦉", "murcielago" to "🦇",
            "pez" to "🐟", "tiburon" to "🦈", "delfin" to "🐬", "pulpo" to "🐙",
            "cangrejo" to "🦀", "ballena" to "🐋",
            "flor" to "🌸", "rosa" to "🌹", "arbol" to "🌳",
            "luna" to "🌙", "sol" to "☀️", "estrella" to "⭐",
            "espada" to "⚔️", "escudo" to "🛡️", "corona" to "👑",
            "corazon" to "❤️", "libro" to "📖", "llave" to "🗝️",
            "misterio" to "🔮", "misteriosa" to "🔮", "secreto" to "🔐",
            "fantasia" to "🧙", "magia" to "🧙", "magico" to "🪄", "magica" to "🪄"
        )
        for ((key, emoji) in rules) {
            if (n.contains(key)) return emoji
        }
        return "⭐"
    }

    private fun normalize(text: String): String {
        return text.lowercase()
            .replace("á", "a").replace("é", "e").replace("í", "i")
            .replace("ó", "o").replace("ú", "u").replace("ü", "u").replace("ñ", "n")
    }
}
